---
title: "Iterate"
data-by-continent: github_document
editor_options: 
  chunk_data-by-continent_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  collapse = TRUE, 
  cache = FALSE, 
  comment = "#>",
  error = TRUE
)
```

```{r}
library(tidyverse)
```

```{r}
messy <- read_csv("data/gap_wide.csv")

messy
```

```{r}
by_continent <- split(messy, messy$continent)
if (interactive()) {
  View(by_continent) 
} else {
  str(by_continent, max.level = 1)
} 
```

Other views:

```{r}
map(by_continent, nrow)

# Each data-by-continent is an integer of lengh 1
map_int(by_continent, nrow)

# vapply(list, function, FUN.VALUE = type, ...)
vapply(by_continent, nrow, FUN.VALUE = double(1))
```

What if purrr has not function for the expected data-by-continent?

```{r}
map(by_continent, dim)

# Fails
try(map_int(by_continent, dim))

# vapply(list, function, FUN.VALUE = type, ...)
vapply(by_continent, dim, FUN.VALUE = integer(2))
```

```{r dir-create-data-by-continent}
if (!fs::dir_exists("data-by-continent")) fs::dir_create("data-by-continent")
```



```{r write-data-by-continent}
(continents <- names(by_continent))
(file_names <- glue::glue("{continents}.csv"))
(paths <- here::here("data-by-continent", file_names))

walk2(by_continent, paths, write_csv)
```

Confirm

```{r dir-ls-data-by-continent}
fs::dir_ls("data-by-continent")
```


