---
title: "Create data/ from data-raw/"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, comment = "#>")
```

This document creates the data in data/ from files in data-raw.

```{r packages}
library(tidyverse)
library(here)
library(vroom)
library(fs)
library(glue)
```

Import `wide` data from data-raw/.

```{r, message=FALSE}
wide <- vroom(here("data-raw", "gap_wide.csv"))
wide
```

Find `continents`.

```{r}
continents <- wide %>% 
  distinct(continent) %>% 
  pull() %>% 
  tolower()
continents
```

Ensure data/by-continent/.

```{r}
by_continent_path <- here("data", "by-continent")
by_continent_path

if (!dir_exists(by_continent_path)) {
  dir_create(by_continent_path)
}
```

Create paths where to later save the data of each continent.

```{r}
paths <- path(by_continent_path, glue("{continents}.csv"))
paths
```

Split data by continent and save it in data/ (side effect with no output).

```{r}
wide %>% 
  group_split(continent) %>% 
  walk2(paths, write_csv)
```

Confirm.

```{r, message=FALSE}
# See files
dir_ls(by_continent_path)
```
